### ISSUE TITLE
Getting kicked for unknown reasons.

### ISSUE THREAD

**Issue by crittyboi** [leighmacdonald/uncletopia#114]
**Is your feature request related to a problem? Please describe.**
It's very hard to play on these servers because I often times get kicked. I'm not sure why. I do have a quite "gay" name and pfp, which I have been kicked for a lot in casual.

**Describe the solution you'd like**
I'm unsure if they kick me on the basis mentioned above. But adding some guidelines would be nice.

**Describe alternatives you've considered**
I'm not sure if there's any really good way to solve this. It's not like you can control the players.

**Comment by JONTTM** [comment]
I would recommend contacting our mods on [Discord]<https://discord.gg/uncledane> and reporting anyone who might be harassing you or kicking from the servers. We can then ban those people.
