### ISSUE TITLE
More Europe Servers

### ISSUE THREAD

**Issue by Pinguinor** [leighmacdonald/uncletopia#115]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when i open the website to play tf2 and all the Europe servers are full and i have to wait 10-20 minutes to play tf2. I cant play in the US servers because there is too much lag (150-200 ms)

**Describe the solution you'd like**

I want to have more Servers at least 1 more server in the UK  . I live in Portugal so it would be great if there was a server in spain because even people from north africa could play with little ping.

**Describe alternatives you've considered**

I thought of other alternatives like improving the anti-lag system, (I'm not the most creative person)

**Additional context**

![image](https://user-images.githubusercontent.com/86967732/124481654-6db4bf80-dda0-11eb-9414-8984bce14965.png)

**Comment by JONTTM** [comment]
I will revisit this when I get a chance to talk to Dane

**Comment by BLessedDed** [comment]
yes a server in spain would be really awesome

**Comment by crescentrose** [comment]
Done :P
