### ISSUE TITLE
End of round map voting sometimes does not select the highest voted map to load as the next map

### ISSUE THREAD

**Issue by ishaaqj** [leighmacdonald/uncletopia#116]
**Describe the bug**
Normally after the end of round map voting, the server loads with the highest voted map. Pretty frequently I've noted that despite a map being voted the highest, the server will choose a random map from the map voting list instead of the highest voted one.

**To Reproduce**
Can't reproduce it consistently since it seems random.

1. Wait for end of round vote
2. Note all the maps and which is the highest voted map
3. When the server changes there is a chance the highest voted map is not loaded and instead another map from the list is loaded

**Expected behavior**

The highest voted map should be loaded as the next map after the round ends.

**Comment by leighmacdonald** [comment]
Should be fixed with the newer UMC plugin.
