### ISSUE TITLE
Buy more servers you cowards

### ISSUE THREAD

**Issue by theAwkwardSilence** [leighmacdonald/uncletopia#117]
**Is your feature request related to a problem? Please describe.**
You haven't bought enough servers and there's hardly ever an available one open. I love these servers but can only get on them once in a blue moon, often on a server halfway around the world.

**Describe the solution you'd like**
Please, if possible, buy at least two or three more servers in the US. They're great and I just want to be able to join one more often. I'm dying out here.

**Describe alternatives you've considered**
An alternative would be to maybe convert some existing servers to 32 player, again if possible. 

**Additional context**
If any of the Dane staff (or Dane himself) end up actually seeing this, thank you so much for all you do, and keep up the great work (Hopefully with a few more servers?)

**Comment by JONTTM** [comment]
It’s up to Dane if we add more servers… not really a money issue. He just doesn’t want too many servers with no players on them, so we carefully add more servers as the existing ones are consistently full throughout the day.

**Comment by JONTTM** [comment]
If the servers are full only during peak hours, then we won’t add more until all are full for more of the day
