### ISSUE TITLE
Unable to connect after map changes / Disconnected randomly

### ISSUE THREAD

**Issue by StrangeKSALex** [leighmacdonald/uncletopia#119]
**Describe the bug**
I fail to connect after a certain time played, usually happens when map changes

**Expected behavior**
Should be able to connect

**Additional context**
I don't get kicked, I just fail to connect, or lose connection in the middle of the match for unknown reasons.
This issue doesn't happen on any other community servers, only uncletopia

This happens everytime I try to play

**Comment by JONTTM** [comment]
I would try using a VPN to connect. It's more likely an issue with your ISP connecting to our ISP

**Comment by AyoEren** [comment]
I'll try that and let y'all know if anything changes
