### ISSUE TITLE
An increase in acceptable ping.

### ISSUE THREAD

**Issue by PhillipoTF2** [leighmacdonald/uncletopia#123]
G'day,
I often find myself unable to play on your servers with friends as I tend to have too high ping which results in me being kicked. My issue with this system is that the ping that is "too high" is often perfectly playable and does not affect me or others. I initially wanted to see the end of the enforcement of these kicks but I could see the likelihood of that occurring is quite low since it does have a solid reason for being there. Thus I would like to propose an increase of the acceptable ping levels so that someone with less than 175 ping is able to play. From my experience of both playing with ping around that levels and playing against people with that ping it is not going to affect the play-ability of the game. This would allow for someone like me to be able to still play with friends without the risk of having to move on to some sh*tty community server which will have more mods than gamebanana can host and would allow me to still play with friends. I may understand that a lot of (mostly) Americans who play tf2 seem to think that this is too high a ping but I as someone who plenty of times have been forced onto US servers can say that a ping of around 175 is not half bad to either play with or against. As such I must implore you to seek a mutual compromise that will allow Europeans to play on at least half of the US servers and yet still prevent those with insanely high ping (Like 200+) from ruining the experience of others.

Many thanks

PS. I do know this is not exactly a feature suggestion but more of a feature adjustment. If I posted this in the wrong place or if this is not the place for such suggestions of adjustments I apologise and I will swiftly move it else where. Also Please avoid dismissing this immediately and instead open up discussion regarding this, That way we can hopefully still work out a decent compromise here which suits both needs.

**Comment by JONTTM** [comment]
It’s not my decision to make. I completely agree with you. I have played with 80-120ms my whole life and have never had an issue, but some of the higher skilled friends of Dane with less than 20ms claim that a player with high ping really changes how the game is played. This is understandable because of how TF2 compensates for high ping and lag which often gives an unfair advantage to those with higher ping. (Most notably in hit scan classes like sniper)

**Comment by JONTTM** [comment]
To note: we initially  had a higher limit but it was requested to be brought down several times.
