### ISSUE TITLE
Remove !scramble

### ISSUE THREAD

**Issue by Arlwiss** [leighmacdonald/uncletopia#126]
**!scramble** tries to balance a game by mixing up the team compositions, as I presume, by going off of points, kills, deaths, and other statistics. Unfortunately more often than not this has far less impact than the map people play on. Scrambling teams doesn't fix much when those players just aren't doing well on that map, on that day. Instead the result is a bad match is rescrambled a few times until the players spend half an hour on the map, everyone realises they're getting sick of it and that scrambling doesn't seem to be able to change the bad taste in their mouths this time around, and they rtv or leave.
**!rtv** does a far better job of letting people start fresh for more balanced matches. It's still a tossup, of course, but more often than not a far fairer one due to different maps having a far better guarantee for changing people's experience on the server than different teams.
**C**onsidering how much it's abused, how little effect it has, and how much unnecessary extra frustration it brings to players, !scramble seems to me more and more to be an unnecessary evil with a very underappreciated alternative in the face of !rtv.
**P**lease consider disabling it.

**Comment by JONTTM** [comment]
Scramble is currently completely random (vanilla tf2 scramble) and it's also used more often to extend the map

**Comment by JONTTM** [comment]
it won't get changed until an official extend map option is available

**Comment by Arlwiss** [comment]
Fair enough, thanks for the response.

**Comment by BLessedDed** [comment]
yeah just add an !extend
