### ISSUE TITLE
audio bug pt.2

### ISSUE THREAD

**Issue by ManButNotMan** [leighmacdonald/uncletopia#145]
**Describe the bug**
Audio is cutting out from my headphones, i'm only submitting this report here because this ONLY happens on uncletopia servers still.

**To Reproduce**
It just happens

**Expected behavior**
When i join the server the sound cuts in and out.

**Screenshots**
n/a

**Additional context**
add me on discord if you want to hear the bug live in action. Axities#0903 (idk if i can get it to transmit via discord)))

If this is a "solve it yourself" type of problem just lmk, thanks.

**Comment by leighmacdonald** [comment]
@ManButNotMan I have changed the code to the lower quality one, lmk if still an issue.
