### ISSUE TITLE
Game end music loop on extend

### ISSUE THREAD

**Issue by leighmacdonald** [leighmacdonald/uncletopia#159]
When extending a map at the end of the game the end game music will continually loop forever until snd_restart.

**Comment by jack-avery** [comment]
technically "fixed" in our version of nativevotes_mapchooser from before where extend sets nextmap -- unless the update fixed increasing maxrounds/winlimit/timelimit as the end scoreboard is up and i am unaware

**Comment by leighmacdonald** [comment]
Yeah, i figure it was just a line i missed somewhere in the diff merge somewhere.
