### ISSUE TITLE
Using unlockable weapons when item servers are down

### ISSUE THREAD

**Issue by Oh-My-Lands** [leighmacdonald/uncletopia#180]
**Is your feature request related to a problem? Please describe.**

It's always frustrating when the item servers go down (especially every Tuesday) and you are confined to stock loadouts. 

**Describe the solution you'd like**

Implement a plugin similar to the one Skial has (I think?) that allows you to equip any item at any time.  
I also found this: https://github.com/punteroo/TF2-Item-Plugins which may or may not be relevant?

**Comment by leighmacdonald** [comment]
I don't think its really worth the effort of adding these types of mods, Even if we do already use some of the prerequisite plugins already for the custom pve mode. 

This also has the additional problem of the fact that this would not only apply during the times where there is item server outages, but all the time, which is not really something we want to have.
