### ISSUE TITLE
Update the tags

### ISSUE THREAD

**Issue by UncleDane** [leighmacdonald/uncletopia#51]
Right now there are only three tags: "uncletopia", "norandomcrits", and "payload". I think adding every map type we run to the tags might attract more players who aren't going to just vote for the payload map every time. It might help with that at least. Seems kinda weird that payload is the only map tag in there when we run a bunch of map types.

**Comment by JONTTM** [comment]
TF2 automatically updates these tags on map change

**Comment by JONTTM** [comment]
I can still add the other map types if you want, we don't actually have payload in the sv_tags but TF2 adds it when the map is payload

**Comment by leighmacdonald** [comment]
Yep, jon is correct, the map type tag gets added to the list automatically. You can see we dont actually have payload listed here: https://github.com/leighmacdonald/uncletopia/blob/master/group_vars/all.yml.example#L6

**Comment by JONTTM** [comment]
Reopening because I want to hear Dane's response to 
> I can still add the other map types if you wan

**Comment by leighmacdonald** [comment]
That's not how the tags are designed to be used.

**Comment by JONTTM** [comment]
Responded on Discord
