### ISSUE TITLE
Determine what changes when deploying

### ISSUE THREAD

**Issue by leighmacdonald** [leighmacdonald/uncletopia#60]
Currently we get 5 changed state items here, this should be zero but the rsync module is changing something.

    PLAY RECAP *************************************************************************************************************
    as1.uncledane.com          : ok=21   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    eu1.uncledane.com          : ok=21   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    eu2.uncledane.com          : ok=21   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    us1.uncledane.com          : ok=21   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    us2.uncledane.com          : ok=21   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    us3.uncledane.com          : ok=21   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    us4.uncledane.com          : ok=21   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    us5.uncledane.com          : ok=21   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    us6.uncledane.com          : ok=21   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by JONTTM** [comment]
The only thing I am aware of that changes each time is plugin.cronjobs.config
