### ISSUE TITLE
Spawn doors look funny during waiting for players time

### ISSUE THREAD

**Issue by JONTTM** [leighmacdonald/uncletopia#72]
https://discord.com/channels/132353223125106688/722832493648150558/816009930963288114

Only on certain maps

**Comment by sapphonie** [comment]
This is caused by your [opendoors plugin](https://github.com/leighmacdonald/uncletopia/blob/master/roles/tf2/files/tf/addons/sourcemod/scripting/openpregamedoors.sp) not opening area portals as well as doors.


Try this plugin -> https://github.com/sapphonie/WaitingDoors
