### ISSUE TITLE
Stopwatch mode is still enabled on some servers/maps

### ISSUE THREAD

**Issue by JONTTM** [leighmacdonald/uncletopia#85]
Please leave a comment if you notice stopwatch mode on a particular server/map.

It's possible that this is only happening after empty server restart which would explain the pl_badwater and inconsistency in reports

**Comment by JONTTM** [comment]
Sydney - pl_badwater
Sydney - cp_steel
Los Angeles - pl_badwater

**Comment by JustCallMeUni** [comment]
Berlin - pl_badwater
