### ISSUE TITLE
Review pure_server_whitelist.txt

### ISSUE THREAD

**Issue by JONTTM** [leighmacdonald/uncletopia#87]
https://discord.com/channels/132353223125106688/722832493648150558/825406434145206294

**Comment by sapphonie** [comment]
As an anticheat person, sv_pure is trivial to bypass (even for legit clients without injecting!), and [does not work properly even if set to the most restrictive whitelist](https://www.teamfortress.tv/51593/cheating-to-hear-spies-is-painfully-easy). It can also cause client crashes and other random errors for clients.
