### ISSUE TITLE
A few ideas.

### ISSUE THREAD

**Issue by Doire5** [leighmacdonald/uncletopia#98]
Hi Dane/Crew,

I just wanted to vent a few ideas I believe would benefit Uncletopia. Firstly, While I was playing on one of the EU servers, the opposing team (RED on Upward) were losing quite badly to which more or less all of them voted to scramble without much say from BLU near the end of the game. I felt that this was a bit unfair to us who wanted to win. To fix this I believe only allowing a scramble to occur in the opening minute or two into the round would benefit the server.

Secondly, I think adding a couple of your favourite community maps would be a lovely addition to Uncletopia.

And lastly, maybe another EU server ;)

I hope this message finds you well Dane/crew, Uncletopia is already perfect how it is,
Kind regards, Daire.

**Comment by UncleDane** [comment]
Hi Doire5,

In my opinion, if one team is losing quite badly - more often than not - the teams are unbalanced and should be scrambled. So in the case you provided, it definitely seems like the vote-scramble option was being used appropriately. I do understand there is frustration when a win is cut short by unbalanced teams later on in a round, but it's just the nature of a community server that allows players to leave and join at will. It's always possible for multiple players to leave one team and be replaced with players who are considerably less skilled than the previous ones. So teams are able to become unbalanced quite easily at any point. So, as it stands, I believe the vote-scramble option being available at any point during a round is fine and should remain how it is. I will take your suggestion into account, though. I've been considering slightly changing the rules surrounding vote-scrambling, such as increasing the percentage of players required to pass, or putting scrambling on a longer cooldown to prevent repeated abuse. In the future as well, our admins are planning on implementing a custom statistics tracker that will better aid us in adding plugins that sort players onto teams better, hopefully resulting in balanced teams more consistently than the entirely random process that exists right now.

As for community maps, I feel like adding even one community map, no matter how well-designed it is, will only open the floodgates of people suggesting more and more maps that are not only unfamiliar to the average TF2 player, but come with their own set of inconveniences (such as requiring new players to download the map, possibly giving them longer connection times, and booting them from a full server before they can connect - or experiencing technical issues that are common on Valve-unapproved maps such as frame drops or lighting issues). But overall, I personally feel like the Casual+ / Vanilla Lite "theme" is what makes Uncletopia appealing and unique, and there are many many other quality TF2 community servers that host a wide variety of community-made maps. I feel like if we start branching out to custom maps, Uncletopia may lose a piece of its appeal that we've come to be so successful with.

I hope I've addressed you concerns, and thanks for taking the time to submit feedback. Hope you continue to enjoy Uncletopia!

**Comment by JONTTM** [comment]
In response to adding another EU server. We just added one last week, so it will be a while before we add another. 

Please reopen this if you have any other questions.
